services:
  postgres:
    image: debezium/postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10
    environment:
      POSTGRES_USER: dbz
      POSTGRES_PASSWORD: dbz
      POSTGRES_DB: cap_stock_db
   

  etl:
   build: 
    context: ./producer
    dockerfile: Dockerfile
   container_name : etl
   depends_on: 
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy 


   env_file:
    - ./producer/.env

  zookeeper:
    image: quay.io/debezium/zookeeper:3.1
    container_name: zookeeper
    ports: ["2181:2181"]

  kafka:
    image: quay.io/debezium/kafka:3.1
    container_name: kafka
    depends_on: [zookeeper]
    ports: ["29092:29092"]
    environment:
      KAFKA_BROKER_ID: 1
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  
  connect:
    image: quay.io/debezium/connect:3.1
    container_name: connect
    depends_on: [kafka]
    ports: ["8083:8083"]
    environment:
      #Bootstrap
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      HOST_NAME: "connect"
      ADVERTISED_HOST_NAME: "connect"
      ADVERTISED_PORT: "8083"
      KAFKA_CONNECT_PLUGIN_PATH: /kafka/connect,/kafka/plugins,/kafka/plugins/kafka-connect-cassandra-sink-1.7.3,/debezium/connect
      
    volumes:
      - ./plugins/kafka-connect-cassandra-sink-1.7.3:/kafka/connect/kafka-connect-cassandra-sink-1.7.3

  cassandra:
    image: cassandra:4.0.19
    container_name: cassandra
    ports:
      - "9042:9042" 
    volumes:
      - cassandra_data:/var/lib/cassandra # Persistent data storage
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1 
      - CASSANDRA_USER=admin 
      - CASSANDRA_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep 'UN'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - postgres

  akhq:
    image: tchiotludo/akhq:latest
    ports: [8080:8080]
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:9092"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
    depends_on: [kafka, connect]



volumes:
  postgres_data:
  grafana_data:
  cassandra_data:
